#!/bin/bash
# source: salt://sls/rootenv/pickup

[ -S /var/spool/postfix/public/pickup ] || {
  logger -p info.daemon -t $0 Creating socket /var/spool/postfix/public/pickup
  mkfifo /var/spool/postfix/public/pickup
  systemctl restart postfix
}


