#!/bin/bash
# source salt://repomirror/repomirror

source /etc/sysconfig/repomirror


[ -d $dstBase ] || {
  # change so that it outputs to stdout... cron pipes this script to logger.
  logger -sp daemon.info -t reposync $dstBase does not exist
  exit -1
}
releasever=$(cat /etc/redhat-release | sed -e "s/^.*release //" | cut -d\. -f1)
RepoDir=${dstBase}/reposync/$releasever
LogDir=/var/log/reposync
mkdir -p $RepoDir
mkdir -p $LogDir

# Create core.xml
# yum-groups-manager -n Core --id=core --save=core.xml --mandatory bash glibc kernel tcpdump openssh-server yum rpm basesystem coreutils xfsprogs xfsdump lsof strace cronie curl dhclient filesystem hostname initscripts iproute iprutils iptables iptables-services iputils irqbalance kbd kexec-tools less man-db ncurses openssh-clients openssh-server parted passwd policycoreutils procps-ng rootfiles rsyslog selinux-policy-targeted setup shadow-utils sudo systemd tar tuned util-linux vim-minimal biosdevname dracut-config-rescue kernel-tools libsysfs linux-firmware lshw microcode_ctl postfix dracut-config-generic dracut-fips dracut-fips-aesni dracut-network initial-setup openssh-keycat rdma-core selinux-policy-mls tboot ntp


function syncit {
        r=$1
        src=""
        echo $r | grep -E "source|src" -q && src='--source'

        before=$(find $RepoDir/$r -name \*.rpm | wc -l)
        logger -p daemon.info -t reposync "syncing $r. $before rpms."

        /usr/bin/reposync -p $RepoDir $src --repoid $r > $LogDir/${r}.log

        after=$(find $RepoDir/$r -name \*.rpm | wc -l)
        logger -p daemon.info -t reposync "completed $r. $after rpms."

        [ $before -ne $after ] && {
                case $r in
                'base')
                        /usr/bin/createrepo -g $RepoDir/$r/repodata/core.xml $RepoDir/$r
                ;;
                'sdl8-baseos')
                        /usr/bin/createrepo -g $RepoDir/$r/repodata/core.xml $RepoDir/$r
                ;;
                *)
                        /usr/bin/createrepo  $RepoDir/$r
                ;;
                esac
        }
        find $RepoDir/$r -type d | xargs chmod a+rx
        find $RepoDir/$r -type f | xargs chmod a+r
}

function sync_loop {
  target_repo=$1
  echo $target_repo --- $RepoDir/$target_repo
  [ -d $RepoDir/$target_repo ] || mkdir $RepoDir/$target_repo
  [ -d $RepoDir/$target_repo ] || echo BARF! failed to  $RepoDir/$target_repo
  [ -d $RepoDir/$target_repo ] && syncit $target_repo
  [ -d $RepoDir/$target_repo ] && rm -f $RepoDir/$target_repo/directory-not-managed
}

for i in $(grep \\[ /etc/yum.repos.d/*.repo | grep -Ev "Vault|Media" | sed -e "s/^.*\[//; s/\].*$//;"); do
  #sync_loop $1 &
  echo $i --- $RepoDir/$i
  [ -d $RepoDir/$i ] || mkdir $RepoDir/$i
  [ -d $RepoDir/$i ] || echo BARF! failed to  $RepoDir/$i
  [ -d $RepoDir/$i ] && syncit $i
  [ -d $RepoDir/$i ] && rm -f $RepoDir/$i/directory-not-managed
done

