#!/bin/bash


cd $(dirname $0)
[ $# -eq 1 ] || { echo Need a host name. ; exit -1; }
host=$1
[ -f ../pki/private/${host}.key ] || { echo Need key file: ./easyrsa gen-req $host nopass; exit -2; }
[ -f ../pki/issued/${host}.crt ] || { echo Need CRT file: ./easyrsa sign-req client $host; exit -3; }

[ \
  "$(openssl rsa -noout -modulus -in ../pki/private/${host}.key | md5sum)" \
  = \
  "$(openssl x509 -noout -modulus -in ../pki/issued/${host}.crt | md5sum)" \
] || {
  echo key does not match signed CRT;
  echo remove $host from pki/index.txt and re-sign the key.
  exit -4;
}

cp ../pki/private/${host}.key eotn.key
cp ../pki/issued/${host}.crt eotn.crt
zip  -r ../zip/${host}.zip . -x makeZip
tar -czvf ../zip/${host}.tgz . --exclude makeZip
rm -f eotn.key eotn.crt

