
# 1. Handle security.txt specifically
location = /security.txt {
  default_type text/plain;
  return 200 "whois 'p ! MC668-ARIN'";
}

location = /.well-known//security.txt {
  default_type text/plain;
  return 200 "whois 'p ! MC668-ARIN'";
}

location = /robots.txt {
    default_type text/plain;
    return 200 "User-agent: *\nDisallow: /\n";
}
