#!/bin/bash
# salt://sls/salt/saltcall

pkill -9 -f salt-call
systemctl status salt-minion >/dev/null 2>&1 && systemctl start salt-minion >/dev/null 2>&1
systemctl status salt-minion >/dev/null 2>&1 || exit
/usr/bin/salt-call state.apply > /var/log/salt-call.log 2>/var/log/salt-call.err
